collision_monitor:
  ros__parameters:
    base_frame_id: base_footprint
    odom_frame_id: odom
    cmd_vel_in_topic: /cmd_vel
    cmd_vel_out_topic: /cmd_vel_safe
    source_timeout: 1.0
    polygons: [stop]
    stop:
      type: polygon
      action_type: stop
      points: "[[-0.7,-0.55],[-0.7,0.55],[1.3,0.55],[1.3,-0.55]]"
      visualize: false
    observation_sources: [scan]
    scan:
      type: scan
      topic: /scan_clean
      source_timeout: 1.0
      min_height: 0.0
      max_height: 2.0
