---
bool ok
string error
bool active
string phase
bool low_battery_active
bool return_home_requested
bool return_home_active
int32 return_exit_loop_index
int32 depart_entry_loop_index
bool home_available
string mission_id
string status
float64 home_lat
float64 home_lon
float64 home_yaw_deg
float64[] loop_lats
float64[] loop_lons
float64[] loop_yaws_deg
string[] loop_action_jsons
float64[] return_lats
float64[] return_lons
float64[] return_yaws_deg
string[] return_action_jsons
float64[] depart_lats
float64[] depart_lons
float64[] depart_yaws_deg
string[] depart_action_jsons
float64[] active_lats
float64[] active_lons
float64[] active_yaws_deg
