---
bool ok
string error
bool active
bool paused
bool loop
bool low_battery_active
bool return_home_requested
bool return_home_active
int32 return_home_exit_waypoint_index
string return_home_phase
bool home_available
string mission_id
uint32 chunk_id
uint32 loop_iteration
uint32 reached_checkpoint_count
uint32 input_waypoint_count
uint32 expanded_waypoint_count
uint32 current_start_index
uint32 current_target_index
uint32 active_chunk_size
float64 leg_spacing_m
float64 chunk_span_m
uint32 chunk_max_waypoints
string status
string blocked_state
string blocked_reason_code
string blocked_reason_text
uint32 blocked_retry_attempt
uint32 blocked_retry_max_attempts
float64 blocked_wait_remaining_s
bool action_active
uint32 action_waypoint_index
string action_type
float64 action_remaining_s
int32 current_checkpoint_index
int32 current_progress_expanded_index
float64 current_progress_ratio
float64 cross_track_error_m
float64 distance_to_target_m
float64 home_lat
float64 home_lon
float64 home_yaw_deg
float64[] mission_lats
float64[] mission_lons
float64[] mission_yaws_deg
string[] mission_action_jsons
string[] mission_waypoint_roles
bool[] mission_key_flags
int32[] mission_input_indices
float64[] active_lats
float64[] active_lons
float64[] active_yaws_deg
