#include <gtest/gtest.h>
#include "salus_navigation_costmap/vector_keepout_geometry.hpp"
using namespace salus_navigation_costmap;

static Polygon square(double x, double y, double size) { Polygon p; p.id = "zone"; p.outer = {{x,y},{x+size,y},{x+size,y+size},{x,y+size}}; p.bounds = bounds_of(p.outer); return p; }
static RasterSpec spec(double x = 0, double y = 0, unsigned w = 10, unsigned h = 10) { return {{x,y,x+w,y+h}, 1.0, w, h}; }
TEST(VectorKeepoutGeometry, RasterizesCoreAndClipsToWindow) { auto costs = rasterize({square(2,2,3)}, spec(), {}); EXPECT_EQ(costs[2 * 10 + 2], 100); EXPECT_EQ(costs[0], 0); EXPECT_EQ(costs.size(), 100u); }
TEST(VectorKeepoutGeometry, HolesAreNotKeepoutCore) { auto p = square(1,1,8); p.holes = {{{3,3},{7,3},{7,7},{3,7}}}; auto costs = rasterize({p}, spec(), {}); EXPECT_LT(costs[4 * 10 + 4], 100); EXPECT_EQ(costs[1 * 10 + 1], 100); }
TEST(VectorKeepoutGeometry, HaloUsesLegacyExponentialProfile) { CostProfile profile; profile.halo_radius_m = 3.0; profile.halo_edge_cost = 60; profile.halo_min_cost = 10; auto costs = rasterize({square(4,4,2)}, spec(), profile); EXPECT_EQ(costs[4 * 10 + 4], 100); EXPECT_GT(costs[4 * 10 + 3], costs[4 * 10 + 1]); EXPECT_GE(costs[4 * 10 + 1], 10); }
TEST(VectorKeepoutGeometry, FarPolygonsDoNotContribute) { auto costs = rasterize({square(1000,1000,5)}, spec(), {}); for (auto value : costs) EXPECT_EQ(value, 0); }
TEST(VectorKeepoutGeometry, MultiplePolygonsAreMergedByMaximum) { CostProfile profile; profile.halo_radius_m = 2.0; auto costs = rasterize({square(2,2,2), square(6,2,2)}, spec(), profile); EXPECT_EQ(costs[2 * 10 + 2], 100); EXPECT_EQ(costs[2 * 10 + 6], 100); EXPECT_GT(costs[2 * 10 + 4], 0); }
TEST(VectorKeepoutGeometry, ConvertsLegacyMaskCostsExactlyLikeKeepoutFilterCostmap) { EXPECT_EQ(legacy_mask_cost_to_nav2_cost(0), 0); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(1), 3); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(3), 8); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(7), 18); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(12), 30); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(60), 152); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(99), 251); EXPECT_EQ(legacy_mask_cost_to_nav2_cost(100), 254); }
TEST(VectorKeepoutLayerPolicy, RemovalAndMoveDirtyOldAndNewBounds) { Bounds window{0,0,30,30}, dirty{}; auto old = square(2,2,2); auto moved = square(20,20,2); ASSERT_TRUE(add_dirty_bounds({old, moved}, window, 0, &dirty)); EXPECT_EQ(dirty.min_x, 2); EXPECT_EQ(dirty.max_x, 22); }
TEST(VectorKeepoutLayerPolicy, GlobalMapUsesIdentityAndLocalUsesMapToOdom) { auto map = square(2,3,1); const auto global = transformed(map, 0, 0, 0); const auto local = transformed(map, 10, -4, 0); EXPECT_EQ(global.bounds.min_x, 2); EXPECT_EQ(local.bounds.min_x, 12); EXPECT_EQ(local.bounds.min_y, -1); }
TEST(VectorKeepoutLayerPolicy, MapToOdomCorrectionDirtiesFormerAndNewPositions) { Bounds dirty{}; const Bounds window{-20,-20,40,40}; auto before = transformed(square(1,1,1), 0, 0, 0); auto after = transformed(square(1,1,1), 10, 0, 0); ASSERT_TRUE(add_dirty_bounds({before, after}, window, 0, &dirty)); EXPECT_EQ(dirty.min_x, 1); EXPECT_EQ(dirty.max_x, 12); }
TEST(VectorKeepoutLayerPolicy, RestartRevisionIsAccepted) { ProjectedState state; replace_state(&state, {square(1,1,1)}, 42); replace_state(&state, {square(8,8,1)}, 1); ASSERT_EQ(state.revision, 1u); ASSERT_EQ(state.previous.size(), 1u); EXPECT_EQ(state.current.front().bounds.min_x, 8); }
TEST(VectorKeepoutLayerPolicy, FarZonesDoNotDirtyRollingWindow) { Bounds dirty{}; EXPECT_FALSE(add_dirty_bounds({square(1000,1000,2)}, {0,0,30,30}, 1.5, &dirty)); EXPECT_TRUE(intersecting({square(1,1,2), square(1000,1000,2)}, {0,0,30,30}, 1.5).size() == 1); }
TEST(VectorKeepoutLayerPolicy, KeepoutReplacesUnknownButNeverLowersKnownCost) { EXPECT_EQ(max_keepout_cost(255, legacy_mask_cost_to_nav2_cost(100)), 254); EXPECT_EQ(max_keepout_cost(200, legacy_mask_cost_to_nav2_cost(60)), 200); EXPECT_EQ(max_keepout_cost(100, legacy_mask_cost_to_nav2_cost(100)), 254); }
